apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-code-with-quarkus-rsze
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-code-with-quarkus-rsze
    app.kubernetes.io/part-of: devfile-sample-code-with-quarkus-1
  name: devfile-sample-code-with-quarkus-rsze
spec:
  ports:
  - name: http-8081
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: java-quarkus-app
    app.kubernetes.io/instance: devfile-sample-code-with-quarkus-rsze
status:
  loadBalancer: {}
